name: M J Gilbert
favicon: null
layout_spectrum: 0.9276730697602034
typography_spectrum: 0.17114285589195788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5469898683950305
  lightness: 0.0463592812884599
  saturation: 0.21938790124841034
  rhythmicContrast: 0.6634598306845874
purpose: []
