typography_spectrum: 0.08002145
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.0424275
title: M J Gilbert
purpose: []
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 0
  brandColors:
    - '#1F1F1F'
    - '#FFFFFF'
    - '#909090'
    - '#4A5360'
    - '#CDCDCD'
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: UA-74177415-1
  facebook: null
name: M. J. Gilbert
