name: M J Gilbert
favicon: null
layout_spectrum: 0.9276730697602034
typography_spectrum: 0.32966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10172b'
    - '#13345f'
    - '#13467d'
    - '#1563a3'
    - '#157eb9'
  brandStrength: 0.5625
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
