name: M. J. Gilbert
favicon: null
layout_spectrum: 0.75149
typography_spectrum: 0.67231
title: M J Gilbert
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74177415-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10172a'
    - '#13335c'
    - '#114d89'
    - '#1775b3'
    - '#198ec4'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
