name: M.J.Gilbert
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b1ea6ad0-27ee-4052-bd3f-ce18e13af69d.png
layout_spectrum: 0.76043
typography_spectrum: 1
title: Michael Gilbert - Editor
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Offline - Online - VFX
author:
  name: Michael Gilbert
  email: michael@mjgilbert.com
  url: mjgilbert.com
navigation:
  - name: Work
    id: e62c1af9-0c6a-4bad-90b6-996bb73bf2df
    type: content
  - name: Contact Me
    id: 3212a1e1-48a1-47f1-9cc7-b552d379755e
    type: content
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a2cfc8ee-02aa-4b2b-a146-27cf7dc49273.png
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74177415-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10172a'
    - '#13335c'
    - '#114d89'
    - '#1775b3'
    - '#198ec4'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
