favicon: null
name: M J Gilbert
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#10172b'
    - '#13345f'
    - '#13467d'
    - '#1563a3'
    - '#157eb9'
  rhythmicContrast: 0
typography_spectrum: 0.6460795
layout_spectrum: 0.8319011
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
