layout_spectrum: 0.3601477744523436
typography_spectrum: 0.3468356600496918
color:
  brandColors:
    - '#0067A4'
    - '#2184BE'
    - '#FFFFFF'
    - '#7FADBD'
    - '#AFD7E5'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
name: M.J.Gilbert
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b1ea6ad0-27ee-4052-bd3f-ce18e13af69d.png
title: Editor
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Offline - Online - VFX
navigation:
  - name: Work
    id: e62c1af9-0c6a-4bad-90b6-996bb73bf2df
    type: content
  - name: Contact Me
    id: 3212a1e1-48a1-47f1-9cc7-b552d379755e
    type: content
author:
  name: Michael Gilbert
  email: michael@mjgilbert.com
  url: mjgilbert.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a2cfc8ee-02aa-4b2b-a146-27cf7dc49273.png
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74177415-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
