name: M. J. Gilbert
favicon: null
layout_spectrum: 0.49209
typography_spectrum: 0.67231
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: M J Gilbert
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74177415-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5577b6'
    - '#779bd7'
    - '#385893'
    - '#04090d'
    - '#012c60'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
