typography_spectrum: 0.32483390998095274
color:
  brandColors:
    - '#13335C'
    - '#1775B3'
    - '#114D89'
    - '#10172A'
    - '#198EC4'
  brandStrength: 0.39687351137399673
  lightness: 0.7610297240316868
  saturation: 0.24291843874379992
  rhythmicContrast: 0.7804435004945844
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6509920749813318
analytics:
  google: UA-74177415-1
  facebook: null
  twitter: null
author:
  name: Michael Gilbert
  email: michael@mjgilbert.com
  url: mjgilbert.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a2cfc8ee-02aa-4b2b-a146-27cf7dc49273.png
name: M.J.Gilbert
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Work
    id: e62c1af9-0c6a-4bad-90b6-996bb73bf2df
    type: content
  - name: Contact Me
    id: 3212a1e1-48a1-47f1-9cc7-b552d379755e
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b1ea6ad0-27ee-4052-bd3f-ce18e13af69d.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Michael Gilbert - Editor
description: "\_Offline // Online // VFX\_"
purpose: []
