title: M J Gilbert
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#1F1F1F'
    - '#FFFFFF'
    - '#909090'
    - '#4A5360'
    - '#CDCDCD'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74177415-1
  facebook: null
name: M. J. Gilbert
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9124597
layout_spectrum: 1
