name: M. J. Gilbert
favicon: null
layout_spectrum: 0.06820623
typography_spectrum: 0.07572501
title: M J Gilbert
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74177415-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2E384C'
    - '#14171F'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.6750805
purpose: []
