typography_spectrum: 0.07572501
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.06820623
title: M J Gilbert
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 0.6750805
  brandColors:
    - '#2E384C'
    - '#14171F'
  lightness: 1
purpose: []
favicon: null
analytics:
  twitter: null
  google: UA-74177415-1
  facebook: null
name: M. J. Gilbert
