favicon: null
name: M J Gilbert
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#2E384C'
    - '#4C5B7F'
    - '#6E9BCE'
  rhythmicContrast: 0.5
typography_spectrum: 0.15305
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.50061
analytics:
  twitter: null
  google: null
  facebook: null
