analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  lightness: 0.5290011
  brandStrength: 0.7416756
  brandColors:
    - '#10172b'
    - '#13345f'
    - '#13467d'
    - '#1563a3'
    - '#157eb9'
  rhythmicContrast: 0.5139635
typography_spectrum: 0.8974221
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: M J Gilbert
