favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 1
  rhythmicContrast: 0.5
  brandColors:
    - '#2E384C'
    - '#4C5B7F'
    - '#6E9BCE'
  lightness: 0
typography_spectrum: 0.7384533
layout_spectrum: 0.698711
analytics:
  twitter: null
  google: null
  facebook: null
name: M J Gilbert
