title: M J Gilbert
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2604726
  brandStrength: 1
  lightness: 0.744898
  brandColors:
    - '#000202'
    - '#FFFFFC'
    - '#315266'
    - '#889191'
    - '#DFDFCF'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: M. J. Gilbert
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5139635
layout_spectrum: 0.7502685
